/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddendumSectionsInput } from './AddendumSectionsInput';
import {
  AddendumSectionsInputFromJSON,
  AddendumSectionsInputFromJSONTyped,
  AddendumSectionsInputToJSON,
  AddendumSectionsInputToJSONTyped,
} from './AddendumSectionsInput';

/**
 *
 * @export
 * @interface AddendumInput
 */
export interface AddendumInput {
  /**
   * 2–3 sentence executive summary of salient updates
   * @type {string}
   * @memberof AddendumInput
   */
  summary: string;
  /**
   *
   * @type {AddendumSectionsInput}
   * @memberof AddendumInput
   */
  sections: AddendumSectionsInput;
}

/**
 * Check if a given object implements the AddendumInput interface.
 */
export function instanceOfAddendumInput(value: object): value is AddendumInput {
  if (!('summary' in value) || value['summary'] === undefined) return false;
  if (!('sections' in value) || value['sections'] === undefined) return false;
  return true;
}

export function AddendumInputFromJSON(json: any): AddendumInput {
  return AddendumInputFromJSONTyped(json, false);
}

export function AddendumInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumInput {
  if (json == null) {
    return json;
  }
  return {
    summary: json['summary'],
    sections: AddendumSectionsInputFromJSON(json['sections']),
  };
}

export function AddendumInputToJSON(json: any): AddendumInput {
  return AddendumInputToJSONTyped(json, false);
}

export function AddendumInputToJSONTyped(value?: AddendumInput | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    summary: value['summary'],
    sections: AddendumSectionsInputToJSON(value['sections']),
  };
}
