/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const AddendumSeverity = {
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;
export type AddendumSeverity = (typeof AddendumSeverity)[keyof typeof AddendumSeverity];

export function instanceOfAddendumSeverity(value: any): boolean {
  for (const key in AddendumSeverity) {
    if (Object.prototype.hasOwnProperty.call(AddendumSeverity, key)) {
      if (AddendumSeverity[key as keyof typeof AddendumSeverity] === value) {
        return true;
      }
    }
  }
  return false;
}

export function AddendumSeverityFromJSON(json: any): AddendumSeverity {
  return AddendumSeverityFromJSONTyped(json, false);
}

export function AddendumSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumSeverity {
  return json as AddendumSeverity;
}

export function AddendumSeverityToJSON(value?: AddendumSeverity | null): any {
  return value as any;
}

export function AddendumSeverityToJSONTyped(value: any, ignoreDiscriminator: boolean): AddendumSeverity {
  return value as AddendumSeverity;
}
