/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddendumSectionsOutput } from './AddendumSectionsOutput';
import {
  AddendumSectionsOutputFromJSON,
  AddendumSectionsOutputFromJSONTyped,
  AddendumSectionsOutputToJSON,
  AddendumSectionsOutputToJSONTyped,
} from './AddendumSectionsOutput';

/**
 *
 * @export
 * @interface AddendumOutput
 */
export interface AddendumOutput {
  /**
   * 2–3 sentence executive summary of salient updates
   * @type {string}
   * @memberof AddendumOutput
   */
  summary: string;
  /**
   *
   * @type {AddendumSectionsOutput}
   * @memberof AddendumOutput
   */
  sections: AddendumSectionsOutput;
}

/**
 * Check if a given object implements the AddendumOutput interface.
 */
export function instanceOfAddendumOutput(value: object): value is AddendumOutput {
  if (!('summary' in value) || value['summary'] === undefined) return false;
  if (!('sections' in value) || value['sections'] === undefined) return false;
  return true;
}

export function AddendumOutputFromJSON(json: any): AddendumOutput {
  return AddendumOutputFromJSONTyped(json, false);
}

export function AddendumOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumOutput {
  if (json == null) {
    return json;
  }
  return {
    summary: json['summary'],
    sections: AddendumSectionsOutputFromJSON(json['sections']),
  };
}

export function AddendumOutputToJSON(json: any): AddendumOutput {
  return AddendumOutputToJSONTyped(json, false);
}

export function AddendumOutputToJSONTyped(value?: AddendumOutput | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    summary: value['summary'],
    sections: AddendumSectionsOutputToJSON(value['sections']),
  };
}
