/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddendumItem } from './AddendumItem';
import {
  AddendumItemFromJSON,
  AddendumItemFromJSONTyped,
  AddendumItemToJSON,
  AddendumItemToJSONTyped,
} from './AddendumItem';

/**
 *
 * @export
 * @interface AddendumSectionsInput
 */
export interface AddendumSectionsInput {
  /**
   *
   * @type {Array<AddendumItem>}
   * @memberof AddendumSectionsInput
   */
  background?: Array<AddendumItem>;
  /**
   *
   * @type {Array<AddendumItem>}
   * @memberof AddendumSectionsInput
   */
  methodology?: Array<AddendumItem>;
  /**
   *
   * @type {Array<AddendumItem>}
   * @memberof AddendumSectionsInput
   */
  results?: Array<AddendumItem>;
  /**
   *
   * @type {Array<AddendumItem>}
   * @memberof AddendumSectionsInput
   */
  interpretation?: Array<AddendumItem>;
}

/**
 * Check if a given object implements the AddendumSectionsInput interface.
 */
export function instanceOfAddendumSectionsInput(value: object): value is AddendumSectionsInput {
  return true;
}

export function AddendumSectionsInputFromJSON(json: any): AddendumSectionsInput {
  return AddendumSectionsInputFromJSONTyped(json, false);
}

export function AddendumSectionsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumSectionsInput {
  if (json == null) {
    return json;
  }
  return {
    background: json['background'] == null ? undefined : (json['background'] as Array<any>).map(AddendumItemFromJSON),
    methodology:
      json['methodology'] == null ? undefined : (json['methodology'] as Array<any>).map(AddendumItemFromJSON),
    results: json['results'] == null ? undefined : (json['results'] as Array<any>).map(AddendumItemFromJSON),
    interpretation:
      json['interpretation'] == null ? undefined : (json['interpretation'] as Array<any>).map(AddendumItemFromJSON),
  };
}

export function AddendumSectionsInputToJSON(json: any): AddendumSectionsInput {
  return AddendumSectionsInputToJSONTyped(json, false);
}

export function AddendumSectionsInputToJSONTyped(
  value?: AddendumSectionsInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    background: value['background'] == null ? undefined : (value['background'] as Array<any>).map(AddendumItemToJSON),
    methodology:
      value['methodology'] == null ? undefined : (value['methodology'] as Array<any>).map(AddendumItemToJSON),
    results: value['results'] == null ? undefined : (value['results'] as Array<any>).map(AddendumItemToJSON),
    interpretation:
      value['interpretation'] == null ? undefined : (value['interpretation'] as Array<any>).map(AddendumItemToJSON),
  };
}
