/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QualityLevel } from './QualityLevel';
import {
  QualityLevelFromJSON,
  QualityLevelFromJSONTyped,
  QualityLevelToJSON,
  QualityLevelToJSONTyped,
} from './QualityLevel';
import type { AddendumSeverity } from './AddendumSeverity';
import {
  AddendumSeverityFromJSON,
  AddendumSeverityFromJSONTyped,
  AddendumSeverityToJSON,
  AddendumSeverityToJSONTyped,
} from './AddendumSeverity';
import type { ReferenceAlignmentLevel } from './ReferenceAlignmentLevel';
import {
  ReferenceAlignmentLevelFromJSON,
  ReferenceAlignmentLevelFromJSONTyped,
  ReferenceAlignmentLevelToJSON,
  ReferenceAlignmentLevelToJSONTyped,
} from './ReferenceAlignmentLevel';
import type { ClaimCategory } from './ClaimCategory';
import {
  ClaimCategoryFromJSON,
  ClaimCategoryFromJSONTyped,
  ClaimCategoryToJSON,
  ClaimCategoryToJSONTyped,
} from './ClaimCategory';
import type { EvidenceWeighterRecommendedAction } from './EvidenceWeighterRecommendedAction';
import {
  EvidenceWeighterRecommendedActionFromJSON,
  EvidenceWeighterRecommendedActionFromJSONTyped,
  EvidenceWeighterRecommendedActionToJSON,
  EvidenceWeighterRecommendedActionToJSONTyped,
} from './EvidenceWeighterRecommendedAction';

/**
 *
 * @export
 * @interface AddendumItem
 */
export interface AddendumItem {
  /**
   *
   * @type {number}
   * @memberof AddendumItem
   */
  chunkIndex: number;
  /**
   *
   * @type {number}
   * @memberof AddendumItem
   */
  claimIndex: number;
  /**
   *
   * @type {string}
   * @memberof AddendumItem
   */
  originalClaim: string;
  /**
   *
   * @type {string}
   * @memberof AddendumItem
   */
  rewrittenClaim: string;
  /**
   *
   * @type {ClaimCategory}
   * @memberof AddendumItem
   */
  claimCategory: ClaimCategory;
  /**
   *
   * @type {ReferenceAlignmentLevel}
   * @memberof AddendumItem
   */
  evidenceAlignment: ReferenceAlignmentLevel;
  /**
   *
   * @type {EvidenceWeighterRecommendedAction}
   * @memberof AddendumItem
   */
  recommendedAction: EvidenceWeighterRecommendedAction;
  /**
   * Two sentences max; actionable guidance on what to change in the claim
   * @type {string}
   * @memberof AddendumItem
   */
  actionSummary: string;
  /**
   *
   * @type {QualityLevel}
   * @memberof AddendumItem
   */
  confidence: QualityLevel;
  /**
   *
   * @type {string}
   * @memberof AddendumItem
   */
  rationale: string;
  /**
   *
   * @type {AddendumSeverity}
   * @memberof AddendumItem
   */
  severity: AddendumSeverity;
}

/**
 * Check if a given object implements the AddendumItem interface.
 */
export function instanceOfAddendumItem(value: object): value is AddendumItem {
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('claimIndex' in value) || value['claimIndex'] === undefined) return false;
  if (!('originalClaim' in value) || value['originalClaim'] === undefined) return false;
  if (!('rewrittenClaim' in value) || value['rewrittenClaim'] === undefined) return false;
  if (!('claimCategory' in value) || value['claimCategory'] === undefined) return false;
  if (!('evidenceAlignment' in value) || value['evidenceAlignment'] === undefined) return false;
  if (!('recommendedAction' in value) || value['recommendedAction'] === undefined) return false;
  if (!('actionSummary' in value) || value['actionSummary'] === undefined) return false;
  if (!('confidence' in value) || value['confidence'] === undefined) return false;
  if (!('rationale' in value) || value['rationale'] === undefined) return false;
  if (!('severity' in value) || value['severity'] === undefined) return false;
  return true;
}

export function AddendumItemFromJSON(json: any): AddendumItem {
  return AddendumItemFromJSONTyped(json, false);
}

export function AddendumItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddendumItem {
  if (json == null) {
    return json;
  }
  return {
    chunkIndex: json['chunk_index'],
    claimIndex: json['claim_index'],
    originalClaim: json['original_claim'],
    rewrittenClaim: json['rewritten_claim'],
    claimCategory: ClaimCategoryFromJSON(json['claim_category']),
    evidenceAlignment: ReferenceAlignmentLevelFromJSON(json['evidence_alignment']),
    recommendedAction: EvidenceWeighterRecommendedActionFromJSON(json['recommended_action']),
    actionSummary: json['action_summary'],
    confidence: QualityLevelFromJSON(json['confidence']),
    rationale: json['rationale'],
    severity: AddendumSeverityFromJSON(json['severity']),
  };
}

export function AddendumItemToJSON(json: any): AddendumItem {
  return AddendumItemToJSONTyped(json, false);
}

export function AddendumItemToJSONTyped(value?: AddendumItem | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    chunk_index: value['chunkIndex'],
    claim_index: value['claimIndex'],
    original_claim: value['originalClaim'],
    rewritten_claim: value['rewrittenClaim'],
    claim_category: ClaimCategoryToJSON(value['claimCategory']),
    evidence_alignment: ReferenceAlignmentLevelToJSON(value['evidenceAlignment']),
    recommended_action: EvidenceWeighterRecommendedActionToJSON(value['recommendedAction']),
    action_summary: value['actionSummary'],
    confidence: QualityLevelToJSON(value['confidence']),
    rationale: value['rationale'],
    severity: AddendumSeverityToJSON(value['severity']),
  };
}
