/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldProblemType } from './FieldProblemType';
import {
  FieldProblemTypeFromJSON,
  FieldProblemTypeFromJSONTyped,
  FieldProblemTypeToJSON,
  FieldProblemTypeToJSONTyped,
} from './FieldProblemType';
import type { FieldCategory } from './FieldCategory';
import {
  FieldCategoryFromJSON,
  FieldCategoryFromJSONTyped,
  FieldCategoryToJSON,
  FieldCategoryToJSONTyped,
} from './FieldCategory';

/**
 *
 * @export
 * @interface BibliographyFieldValidation
 */
export interface BibliographyFieldValidation {
  /**
   * Category of the reference.
   * @type {FieldCategory}
   * @memberof BibliographyFieldValidation
   */
  category: FieldCategory;
  /**
   * Current value of the reference.
   * @type {string}
   * @memberof BibliographyFieldValidation
   */
  currentValue: string;
  /**
   * Suggested value of the reference.
   * @type {string}
   * @memberof BibliographyFieldValidation
   */
  suggestedValue: string;
  /**
   * Problem type of the reference.
   * @type {FieldProblemType}
   * @memberof BibliographyFieldValidation
   */
  problemType: FieldProblemType;
}

/**
 * Check if a given object implements the BibliographyFieldValidation interface.
 */
export function instanceOfBibliographyFieldValidation(value: object): value is BibliographyFieldValidation {
  if (!('category' in value) || value['category'] === undefined) return false;
  if (!('currentValue' in value) || value['currentValue'] === undefined) return false;
  if (!('suggestedValue' in value) || value['suggestedValue'] === undefined) return false;
  if (!('problemType' in value) || value['problemType'] === undefined) return false;
  return true;
}

export function BibliographyFieldValidationFromJSON(json: any): BibliographyFieldValidation {
  return BibliographyFieldValidationFromJSONTyped(json, false);
}

export function BibliographyFieldValidationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BibliographyFieldValidation {
  if (json == null) {
    return json;
  }
  return {
    category: FieldCategoryFromJSON(json['category']),
    currentValue: json['current_value'],
    suggestedValue: json['suggested_value'],
    problemType: FieldProblemTypeFromJSON(json['problem_type']),
  };
}

export function BibliographyFieldValidationToJSON(json: any): BibliographyFieldValidation {
  return BibliographyFieldValidationToJSONTyped(json, false);
}

export function BibliographyFieldValidationToJSONTyped(
  value?: BibliographyFieldValidation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category: FieldCategoryToJSON(value['category']),
    current_value: value['currentValue'],
    suggested_value: value['suggestedValue'],
    problem_type: FieldProblemTypeToJSON(value['problemType']),
  };
}
