/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BibliographyItem } from './BibliographyItem';
import {
  BibliographyItemFromJSON,
  BibliographyItemFromJSONTyped,
  BibliographyItemToJSON,
  BibliographyItemToJSONTyped,
} from './BibliographyItem';
import type { BibliographyFieldValidation } from './BibliographyFieldValidation';
import {
  BibliographyFieldValidationFromJSON,
  BibliographyFieldValidationFromJSONTyped,
  BibliographyFieldValidationToJSON,
  BibliographyFieldValidationToJSONTyped,
} from './BibliographyFieldValidation';

/**
 *
 * @export
 * @interface BibliographyItemValidationInput
 */
export interface BibliographyItemValidationInput {
  /**
   * Original bibliographic item text.
   * @type {BibliographyItem}
   * @memberof BibliographyItemValidationInput
   */
  originalReference: BibliographyItem;
  /**
   * Whether the original reference is valid.
   * @type {boolean}
   * @memberof BibliographyItemValidationInput
   */
  validReference: boolean;
  /**
   * List of reference field validations.
   * @type {Array<BibliographyFieldValidation>}
   * @memberof BibliographyItemValidationInput
   */
  bibliographyFieldValidations: Array<BibliographyFieldValidation>;
  /**
   * Suggested action to take if the reference is not valid. A summary of the suggested changes to make the reference valid. If the reference is valid, return 'No changes needed'.
   * @type {string}
   * @memberof BibliographyItemValidationInput
   */
  suggestedAction: string;
  /**
   * Found URL for the reference.
   * @type {string}
   * @memberof BibliographyItemValidationInput
   */
  url: string;
}

/**
 * Check if a given object implements the BibliographyItemValidationInput interface.
 */
export function instanceOfBibliographyItemValidationInput(value: object): value is BibliographyItemValidationInput {
  if (!('originalReference' in value) || value['originalReference'] === undefined) return false;
  if (!('validReference' in value) || value['validReference'] === undefined) return false;
  if (!('bibliographyFieldValidations' in value) || value['bibliographyFieldValidations'] === undefined) return false;
  if (!('suggestedAction' in value) || value['suggestedAction'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  return true;
}

export function BibliographyItemValidationInputFromJSON(json: any): BibliographyItemValidationInput {
  return BibliographyItemValidationInputFromJSONTyped(json, false);
}

export function BibliographyItemValidationInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BibliographyItemValidationInput {
  if (json == null) {
    return json;
  }
  return {
    originalReference: BibliographyItemFromJSON(json['original_reference']),
    validReference: json['valid_reference'],
    bibliographyFieldValidations: (json['bibliography_field_validations'] as Array<any>).map(
      BibliographyFieldValidationFromJSON,
    ),
    suggestedAction: json['suggested_action'],
    url: json['url'],
  };
}

export function BibliographyItemValidationInputToJSON(json: any): BibliographyItemValidationInput {
  return BibliographyItemValidationInputToJSONTyped(json, false);
}

export function BibliographyItemValidationInputToJSONTyped(
  value?: BibliographyItemValidationInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    original_reference: BibliographyItemToJSON(value['originalReference']),
    valid_reference: value['validReference'],
    bibliography_field_validations: (value['bibliographyFieldValidations'] as Array<any>).map(
      BibliographyFieldValidationToJSON,
    ),
    suggested_action: value['suggestedAction'],
    url: value['url'],
  };
}
