/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentIssueOutput } from './DocumentIssueOutput';
import {
  DocumentIssueOutputFromJSON,
  DocumentIssueOutputFromJSONTyped,
  DocumentIssueOutputToJSON,
  DocumentIssueOutputToJSONTyped,
} from './DocumentIssueOutput';
import type { DocumentChunkOutput } from './DocumentChunkOutput';
import {
  DocumentChunkOutputFromJSON,
  DocumentChunkOutputFromJSONTyped,
  DocumentChunkOutputToJSON,
  DocumentChunkOutputToJSONTyped,
} from './DocumentChunkOutput';
import type { FileDocument } from './FileDocument';
import {
  FileDocumentFromJSON,
  FileDocumentFromJSONTyped,
  FileDocumentToJSON,
  FileDocumentToJSONTyped,
} from './FileDocument';
import type { EvidenceWeighterResponseWithClaimIndexOutput } from './EvidenceWeighterResponseWithClaimIndexOutput';
import {
  EvidenceWeighterResponseWithClaimIndexOutputFromJSON,
  EvidenceWeighterResponseWithClaimIndexOutputFromJSONTyped,
  EvidenceWeighterResponseWithClaimIndexOutputToJSON,
  EvidenceWeighterResponseWithClaimIndexOutputToJSONTyped,
} from './EvidenceWeighterResponseWithClaimIndexOutput';
import type { BibliographyItem } from './BibliographyItem';
import {
  BibliographyItemFromJSON,
  BibliographyItemFromJSONTyped,
  BibliographyItemToJSON,
  BibliographyItemToJSONTyped,
} from './BibliographyItem';
import type { WorkflowError } from './WorkflowError';
import {
  WorkflowErrorFromJSON,
  WorkflowErrorFromJSONTyped,
  WorkflowErrorToJSON,
  WorkflowErrorToJSONTyped,
} from './WorkflowError';
import type { LiteratureReviewResponseOutput } from './LiteratureReviewResponseOutput';
import {
  LiteratureReviewResponseOutputFromJSON,
  LiteratureReviewResponseOutputFromJSONTyped,
  LiteratureReviewResponseOutputToJSON,
  LiteratureReviewResponseOutputToJSONTyped,
} from './LiteratureReviewResponseOutput';
import type { SubstantiationWorkflowConfig } from './SubstantiationWorkflowConfig';
import {
  SubstantiationWorkflowConfigFromJSON,
  SubstantiationWorkflowConfigFromJSONTyped,
  SubstantiationWorkflowConfigToJSON,
  SubstantiationWorkflowConfigToJSONTyped,
} from './SubstantiationWorkflowConfig';
import type { DocumentSummary } from './DocumentSummary';
import {
  DocumentSummaryFromJSON,
  DocumentSummaryFromJSONTyped,
  DocumentSummaryToJSON,
  DocumentSummaryToJSONTyped,
} from './DocumentSummary';
import type { AddendumOutput } from './AddendumOutput';
import {
  AddendumOutputFromJSON,
  AddendumOutputFromJSONTyped,
  AddendumOutputToJSON,
  AddendumOutputToJSONTyped,
} from './AddendumOutput';
import type { BibliographyItemValidationOutput } from './BibliographyItemValidationOutput';
import {
  BibliographyItemValidationOutputFromJSON,
  BibliographyItemValidationOutputFromJSONTyped,
  BibliographyItemValidationOutputToJSON,
  BibliographyItemValidationOutputToJSONTyped,
} from './BibliographyItemValidationOutput';

/**
 *
 * @export
 * @interface ClaimSubstantiatorStateOutput
 */
export interface ClaimSubstantiatorStateOutput {
  /**
   *
   * @type {FileDocument}
   * @memberof ClaimSubstantiatorStateOutput
   */
  file: FileDocument;
  /**
   *
   * @type {Array<FileDocument>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  supportingFiles?: Array<FileDocument> | null;
  /**
   *
   * @type {SubstantiationWorkflowConfig}
   * @memberof ClaimSubstantiatorStateOutput
   */
  config: SubstantiationWorkflowConfig;
  /**
   *
   * @type {string}
   * @memberof ClaimSubstantiatorStateOutput
   */
  workflowRunId?: string | null;
  /**
   *
   * @type {Array<BibliographyItem>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  references?: Array<BibliographyItem>;
  /**
   *
   * @type {Array<BibliographyItemValidationOutput>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  referencesValidated?: Array<BibliographyItemValidationOutput>;
  /**
   *
   * @type {Array<DocumentChunkOutput>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  chunks?: Array<DocumentChunkOutput>;
  /**
   * Errors that occurred during the processing of the document.
   * @type {Array<WorkflowError>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  errors?: Array<WorkflowError>;
  /**
   *
   * @type {DocumentSummary}
   * @memberof ClaimSubstantiatorStateOutput
   */
  mainDocumentSummary?: DocumentSummary | null;
  /**
   *
   * @type {{ [key: string]: DocumentSummary; }}
   * @memberof ClaimSubstantiatorStateOutput
   */
  supportingDocumentsSummaries?: { [key: string]: DocumentSummary } | null;
  /**
   * Live reports analysis results by chunk index
   * @type {Array<EvidenceWeighterResponseWithClaimIndexOutput>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  liveReportsAnalysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  /**
   *
   * @type {LiteratureReviewResponseOutput}
   * @memberof ClaimSubstantiatorStateOutput
   */
  literatureReview?: LiteratureReviewResponseOutput | null;
  /**
   *
   * @type {AddendumOutput}
   * @memberof ClaimSubstantiatorStateOutput
   */
  addendum?: AddendumOutput | null;
  /**
   * Ranked list of document issues with severity levels
   * @type {Array<DocumentIssueOutput>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  rankedIssues?: Array<DocumentIssueOutput>;
}

/**
 * Check if a given object implements the ClaimSubstantiatorStateOutput interface.
 */
export function instanceOfClaimSubstantiatorStateOutput(value: object): value is ClaimSubstantiatorStateOutput {
  if (!('file' in value) || value['file'] === undefined) return false;
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function ClaimSubstantiatorStateOutputFromJSON(json: any): ClaimSubstantiatorStateOutput {
  return ClaimSubstantiatorStateOutputFromJSONTyped(json, false);
}

export function ClaimSubstantiatorStateOutputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClaimSubstantiatorStateOutput {
  if (json == null) {
    return json;
  }
  return {
    file: FileDocumentFromJSON(json['file']),
    supportingFiles:
      json['supporting_files'] == null ? undefined : (json['supporting_files'] as Array<any>).map(FileDocumentFromJSON),
    config: SubstantiationWorkflowConfigFromJSON(json['config']),
    workflowRunId: json['workflow_run_id'] == null ? undefined : json['workflow_run_id'],
    references:
      json['references'] == null ? undefined : (json['references'] as Array<any>).map(BibliographyItemFromJSON),
    referencesValidated:
      json['references_validated'] == null
        ? undefined
        : (json['references_validated'] as Array<any>).map(BibliographyItemValidationOutputFromJSON),
    chunks: json['chunks'] == null ? undefined : (json['chunks'] as Array<any>).map(DocumentChunkOutputFromJSON),
    errors: json['errors'] == null ? undefined : (json['errors'] as Array<any>).map(WorkflowErrorFromJSON),
    mainDocumentSummary:
      json['main_document_summary'] == null ? undefined : DocumentSummaryFromJSON(json['main_document_summary']),
    supportingDocumentsSummaries:
      json['supporting_documents_summaries'] == null
        ? undefined
        : mapValues(json['supporting_documents_summaries'], DocumentSummaryFromJSON),
    liveReportsAnalysis:
      json['live_reports_analysis'] == null
        ? undefined
        : (json['live_reports_analysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexOutputFromJSON),
    literatureReview:
      json['literature_review'] == null ? undefined : LiteratureReviewResponseOutputFromJSON(json['literature_review']),
    addendum: json['addendum'] == null ? undefined : AddendumOutputFromJSON(json['addendum']),
    rankedIssues:
      json['ranked_issues'] == null
        ? undefined
        : (json['ranked_issues'] as Array<any>).map(DocumentIssueOutputFromJSON),
  };
}

export function ClaimSubstantiatorStateOutputToJSON(json: any): ClaimSubstantiatorStateOutput {
  return ClaimSubstantiatorStateOutputToJSONTyped(json, false);
}

export function ClaimSubstantiatorStateOutputToJSONTyped(
  value?: ClaimSubstantiatorStateOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    file: FileDocumentToJSON(value['file']),
    supporting_files:
      value['supportingFiles'] == null ? undefined : (value['supportingFiles'] as Array<any>).map(FileDocumentToJSON),
    config: SubstantiationWorkflowConfigToJSON(value['config']),
    workflow_run_id: value['workflowRunId'],
    references:
      value['references'] == null ? undefined : (value['references'] as Array<any>).map(BibliographyItemToJSON),
    references_validated:
      value['referencesValidated'] == null
        ? undefined
        : (value['referencesValidated'] as Array<any>).map(BibliographyItemValidationOutputToJSON),
    chunks: value['chunks'] == null ? undefined : (value['chunks'] as Array<any>).map(DocumentChunkOutputToJSON),
    errors: value['errors'] == null ? undefined : (value['errors'] as Array<any>).map(WorkflowErrorToJSON),
    main_document_summary: DocumentSummaryToJSON(value['mainDocumentSummary']),
    supporting_documents_summaries:
      value['supportingDocumentsSummaries'] == null
        ? undefined
        : mapValues(value['supportingDocumentsSummaries'], DocumentSummaryToJSON),
    live_reports_analysis:
      value['liveReportsAnalysis'] == null
        ? undefined
        : (value['liveReportsAnalysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexOutputToJSON),
    literature_review: LiteratureReviewResponseOutputToJSON(value['literatureReview']),
    addendum: AddendumOutputToJSON(value['addendum']),
    ranked_issues:
      value['rankedIssues'] == null ? undefined : (value['rankedIssues'] as Array<any>).map(DocumentIssueOutputToJSON),
  };
}
