/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Value } from './Value';
import { ValueFromJSON, ValueFromJSONTyped, ValueToJSON, ValueToJSONTyped } from './Value';

/**
 * A recursive data model for storing custom key-value pairs with context.
 *
 * The value can be either a string or a list of other ContextData objects,
 * allowing for nested structures of labeled data.
 * @export
 * @interface ContextDataInput
 */
export interface ContextDataInput {
  /**
   * The label for this context data entry
   * @type {string}
   * @memberof ContextDataInput
   */
  label: string;
  /**
   *
   * @type {Value}
   * @memberof ContextDataInput
   */
  value: Value;
}

/**
 * Check if a given object implements the ContextDataInput interface.
 */
export function instanceOfContextDataInput(value: object): value is ContextDataInput {
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('value' in value) || value['value'] === undefined) return false;
  return true;
}

export function ContextDataInputFromJSON(json: any): ContextDataInput {
  return ContextDataInputFromJSONTyped(json, false);
}

export function ContextDataInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextDataInput {
  if (json == null) {
    return json;
  }
  return {
    label: json['label'],
    value: ValueFromJSON(json['value']),
  };
}

export function ContextDataInputToJSON(json: any): ContextDataInput {
  return ContextDataInputToJSONTyped(json, false);
}

export function ContextDataInputToJSONTyped(
  value?: ContextDataInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    label: value['label'],
    value: ValueToJSON(value['value']),
  };
}
