/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Value1 } from './Value1';
import { Value1FromJSON, Value1FromJSONTyped, Value1ToJSON, Value1ToJSONTyped } from './Value1';

/**
 * A recursive data model for storing custom key-value pairs with context.
 *
 * The value can be either a string or a list of other ContextData objects,
 * allowing for nested structures of labeled data.
 * @export
 * @interface ContextDataOutput
 */
export interface ContextDataOutput {
  /**
   * The label for this context data entry
   * @type {string}
   * @memberof ContextDataOutput
   */
  label: string;
  /**
   *
   * @type {Value1}
   * @memberof ContextDataOutput
   */
  value: Value1;
}

/**
 * Check if a given object implements the ContextDataOutput interface.
 */
export function instanceOfContextDataOutput(value: object): value is ContextDataOutput {
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('value' in value) || value['value'] === undefined) return false;
  return true;
}

export function ContextDataOutputFromJSON(json: any): ContextDataOutput {
  return ContextDataOutputFromJSONTyped(json, false);
}

export function ContextDataOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextDataOutput {
  if (json == null) {
    return json;
  }
  return {
    label: json['label'],
    value: Value1FromJSON(json['value']),
  };
}

export function ContextDataOutputToJSON(json: any): ContextDataOutput {
  return ContextDataOutputToJSONTyped(json, false);
}

export function ContextDataOutputToJSONTyped(
  value?: ContextDataOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    label: value['label'],
    value: Value1ToJSON(value['value']),
  };
}
