/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeverityEnum } from './SeverityEnum';
import {
  SeverityEnumFromJSON,
  SeverityEnumFromJSONTyped,
  SeverityEnumToJSON,
  SeverityEnumToJSONTyped,
} from './SeverityEnum';
import type { ClaimCategory } from './ClaimCategory';
import {
  ClaimCategoryFromJSON,
  ClaimCategoryFromJSONTyped,
  ClaimCategoryToJSON,
  ClaimCategoryToJSONTyped,
} from './ClaimCategory';
import type { ContextDataInput } from './ContextDataInput';
import {
  ContextDataInputFromJSON,
  ContextDataInputFromJSONTyped,
  ContextDataInputToJSON,
  ContextDataInputToJSONTyped,
} from './ContextDataInput';

/**
 *
 * @export
 * @interface DocumentIssueInput
 */
export interface DocumentIssueInput {
  /**
   * The title of the issue
   * @type {string}
   * @memberof DocumentIssueInput
   */
  title: string;
  /**
   * The description of the issue
   * @type {string}
   * @memberof DocumentIssueInput
   */
  description: string;
  /**
   * The severity of the issue
   * @type {SeverityEnum}
   * @memberof DocumentIssueInput
   */
  severity: SeverityEnum;
  /**
   *
   * @type {string}
   * @memberof DocumentIssueInput
   */
  additionalContext?: string | null;
  /**
   * Custom context data with structured label-value pairs, including more details about the issue and/or context of the issue
   * @type {Array<ContextDataInput>}
   * @memberof DocumentIssueInput
   */
  contextData?: Array<ContextDataInput>;
  /**
   *
   * @type {number}
   * @memberof DocumentIssueInput
   */
  chunkIndex?: number | null;
  /**
   *
   * @type {number}
   * @memberof DocumentIssueInput
   */
  claimIndex?: number | null;
  /**
   *
   * @type {ClaimCategory}
   * @memberof DocumentIssueInput
   */
  claimCategory?: ClaimCategory | null;
}

/**
 * Check if a given object implements the DocumentIssueInput interface.
 */
export function instanceOfDocumentIssueInput(value: object): value is DocumentIssueInput {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('severity' in value) || value['severity'] === undefined) return false;
  return true;
}

export function DocumentIssueInputFromJSON(json: any): DocumentIssueInput {
  return DocumentIssueInputFromJSONTyped(json, false);
}

export function DocumentIssueInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentIssueInput {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    description: json['description'],
    severity: SeverityEnumFromJSON(json['severity']),
    additionalContext: json['additional_context'] == null ? undefined : json['additional_context'],
    contextData:
      json['context_data'] == null ? undefined : (json['context_data'] as Array<any>).map(ContextDataInputFromJSON),
    chunkIndex: json['chunk_index'] == null ? undefined : json['chunk_index'],
    claimIndex: json['claim_index'] == null ? undefined : json['claim_index'],
    claimCategory: json['claim_category'] == null ? undefined : ClaimCategoryFromJSON(json['claim_category']),
  };
}

export function DocumentIssueInputToJSON(json: any): DocumentIssueInput {
  return DocumentIssueInputToJSONTyped(json, false);
}

export function DocumentIssueInputToJSONTyped(
  value?: DocumentIssueInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    description: value['description'],
    severity: SeverityEnumToJSON(value['severity']),
    additional_context: value['additionalContext'],
    context_data:
      value['contextData'] == null ? undefined : (value['contextData'] as Array<any>).map(ContextDataInputToJSON),
    chunk_index: value['chunkIndex'],
    claim_index: value['claimIndex'],
    claim_category: ClaimCategoryToJSON(value['claimCategory']),
  };
}
