/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const FieldCategory = {
  Author: 'author',
  Title: 'title',
  Publisher: 'publisher',
  Year: 'year',
} as const;
export type FieldCategory = (typeof FieldCategory)[keyof typeof FieldCategory];

export function instanceOfFieldCategory(value: any): boolean {
  for (const key in FieldCategory) {
    if (Object.prototype.hasOwnProperty.call(FieldCategory, key)) {
      if (FieldCategory[key as keyof typeof FieldCategory] === value) {
        return true;
      }
    }
  }
  return false;
}

export function FieldCategoryFromJSON(json: any): FieldCategory {
  return FieldCategoryFromJSONTyped(json, false);
}

export function FieldCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldCategory {
  return json as FieldCategory;
}

export function FieldCategoryToJSON(value?: FieldCategory | null): any {
  return value as any;
}

export function FieldCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): FieldCategory {
  return value as FieldCategory;
}
