/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const FieldProblemType = {
  Correct: 'correct',
  Missing: 'missing',
  Incorrect: 'incorrect',
  Other: 'other',
} as const;
export type FieldProblemType = (typeof FieldProblemType)[keyof typeof FieldProblemType];

export function instanceOfFieldProblemType(value: any): boolean {
  for (const key in FieldProblemType) {
    if (Object.prototype.hasOwnProperty.call(FieldProblemType, key)) {
      if (FieldProblemType[key as keyof typeof FieldProblemType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function FieldProblemTypeFromJSON(json: any): FieldProblemType {
  return FieldProblemTypeFromJSONTyped(json, false);
}

export function FieldProblemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldProblemType {
  return json as FieldProblemType;
}

export function FieldProblemTypeToJSON(value?: FieldProblemType | null): any {
  return value as any;
}

export function FieldProblemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FieldProblemType {
  return value as FieldProblemType;
}
