/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContextDataOutput } from './ContextDataOutput';
import {
  ContextDataOutputFromJSON,
  ContextDataOutputFromJSONTyped,
  ContextDataOutputToJSON,
  ContextDataOutputToJSONTyped,
} from './ContextDataOutput';

/**
 * The value, which can be a string or a list of nested ContextData objects
 * @export
 * @interface Value1
 */
export interface Value1 {}

/**
 * Check if a given object implements the Value1 interface.
 */
export function instanceOfValue1(value: object): value is Value1 {
  return true;
}

export function Value1FromJSON(json: any): Value1 {
  return Value1FromJSONTyped(json, false);
}

export function Value1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Value1 {
  return json;
}

export function Value1ToJSON(json: any): Value1 {
  return Value1ToJSONTyped(json, false);
}

export function Value1ToJSONTyped(value?: Value1 | null, ignoreDiscriminator: boolean = false): any {
  return value;
}
